language: node_js
node_js:
- '6'
install:
- npm install
script:
- npm run build
- npm start&
- npm run ci
addons:
  sauce_connect:
    username: SkyZH
    access_key:
      secure: Gpr83yRwyQ5oBPBb+tG6pYS6jTOdbw7XX90B9IMVQDbH9RLsJM5PTMSce5K5nUCoNnZtd2eECpKt5Tj3wDCrQUnQK6QricOsrt92EcoDmtH3Xf66cN7QPQ/2jGlDptE9h6smcPI612xVyIDC1wC/n9jcYJsfTxb+WolTDb9IMsFapDow4+zRPDLWawGirlP+dC3cIUWFzYonng2Bk+WrV+ybhDeRnnBkpBqSldBBvEnzEve0sWTiafMq2Ey6exa80YU63ZsrIi3pDt9vn0r9iIe3jIm8n+gnnHBVIPIgSUo0SGn9QGGPBq/iqIGFiieCXYKeRvO50ZGlr7657wFlVZBMvhqy3ZruitM3rzLWBfFqu7P50BW5E+WOXyON77ZMS2eDirxePD+joeMS4xfaHUNTZ7NM46knAOP83SZjODnZOg8QpKbf5DRCZ2caIZYV0c6O0o8zwLQ6OBmzhyXamzycYVkevw/5avLE6lgX9dnFvuGg0lNjmNIU+XhfcSDadP6UOO2i1vvoZQ4aerg4eyOF/T/Yvxx+LiK75mLfUkRQqK1K2Ee2F4pQIKvDHQ5rP5hEbxqIk5wioRKEkkfjPygVT2Zu9i9ugi3eUoPRabFe4bFyTb/N7FSZmbv70CFGU71JJs+JkKeaWVVWNe8SgM7YH485D1EGUASXxHTa4kA=
notifications:
  slack:
    secure: SB45mBvwfpkABpq1IxGdZ+eGdKcABGpQksOT2HoOImi6hMyj14+iNadFHM3kzMXf+wCTzKTtDM8tW2IT5Z56C48Ofv0yFa/j6+KXObC1Us5kbCcocpR1Emj9uxGCH6Bxf74bNGftcA2AMxD84LbkBqzUy53rXhW4hpwyO8BZ5yXKXAixHvFlK9kabK1Nid301XI0CRYzaYsgmcw6yG4MCdGPT5+/XLH6dPz+Cbei4ExOfU59dzJnMWyazYAHzbksYocdJuY7oOOBy3T2QwoyUjfXcIqHchFY6RiMhBdQKVh7hOpb3id7yH/efPFd0gzsiEB3MrzCgx6CU99wis6uyWjjRKZ+9Q3p9mygI1a6wdSifW5P+SvcPrtNGYtTUdpZ8tNdhNAXoRDI2FT1dkaLpGR7+xdK0xBEXYWkDuCqItkLXy+/zbdpWahNBcbiz3WNmMgc/q+jiMcSN/QILX64aoH97VtNrVzplnYbrQ+iKcwmYMd7xy6u9gr+U4uIZ2ippEmBWBJfZn8+AHQgOUZmvPgAoM9Y8Js5NjHVuOY5OcmVik1WiROwjo7gPSi+NFxeIQpJWjdFx4wdaqoUKx/6HsjWOiC0aQhtgYMhAFY+j1VAn25QHq5QdUhN5lSG9gvPuhTMTT48E6iZl+RPca6t5KZhZ5C93hd5g5YhDwQmZbc=
